spring:
  application:
    name: feign
eureka:
  client:
    service-url:
      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/,http://peer3:7003/eureka/
server:
  port: 7005
feign:
  hystrix:
    enabled: true